package com.javacodegeeks.patterns.templatepattern;


/*
* The connection template pattern 
*/



/*
For MYSQL....
Setting MySQL DB drivers...
Setting credentials for MySQL DB...
Setting connection...
Preparing insert statement...
Setting up data from csv file....
Inserting data...
Closing connections...
Destroying connection objects... 

For Oracle...
Setting Oracle DB drivers...
Setting credentials for Oracle DB...
Setting connection...
Preparing insert statement...
Setting up data from txt file....
Inserting data...
Closing connections...
Destroying connection objects...
*/
public class TestTemplatePattern {


	public static void main(String[] args) {

		System.out.println("For MYSQL....");
		ConnectionTemplate template = new MySqLCSVCon();
		template.run();
		
		System.out.println("\nFor Oracle...");
		template = new OracleTxtCon();
		template.run();
	}
}
